- docs/docs/run-source.rst
Feedback from a user that the installation instructions could be improved.
> Clearer installation instructions and fix jar filename in command

- docs/_templates/index.html
By default if a title isn't set for a given page, sphinx has a default format it tries to follow which includes the project name, page name and some format for it. In our custom index page the title turned out however to be " - Klaw" which isn't optimal for SEO and this commit changes the title to "Home - Klaw"
> Make homepage html title "Home - Klaw"

- docs/conf.py
- `color-admonition-background` has a  white color as standard for OS light mode
- we're reusing the `light_css_variables` also for dark-mode, which is applied based on OS setting  (or local storage)
- the background needed to be set explicit so it's also applied when dark mode is used, otherwise the background was black and text not readable
I checked the site visually (running it locally) with my OS settings for dark and light mode and it looks good.
> Add variable for admonition background to fix appearance in dark mode.

- docs/docs/run-source.rst
Klaw as Maven multi-module project. Modules : 'core' and 'cluster-api'.
'core' Core Api with user interface and cluster-api connectivity
'cluster-api' module is cloned from main branch of repo https://github.com/aiven/klaw-cluster-api. Cluster Api with connectivity to kafka clusters
This removes the dependency on cluster-api git repository.
> Release 1.1.0 with multi maven modules in klaw.

- docs/docs/concepts/promotion.rst
- docs/docs/howto/clusterconnectivity/aiven-kafka-cluster-sasl-ssl-protocol.rst
- docs/docs/howto/clusterconnectivity/aiven-kafka-cluster-ssl-protocol.rst
- docs/docs/howto/clusterconnectivity/aiven-kafka-connect-cluster-ssl-protocol.rst
- docs/docs/howto/clusterconnectivity/aiven-karapace-cluster-ssl-protocol.rst
- docs/docs/howto/clusterconnectivity/kafka-cluster-sasl-ssl-protocol.rst
- docs/docs/howto/clusterconnectivity/kafka-cluster-ssl-protocol.rst
- docs/docs/howto/clusterconnectivity/sr-cluster-ssl-protocol.rst
About this change - What it does
This change adds documentation on how promotion of Topics and Schemas work, including server configuration required to be set up by the superadmin.
This change also adds some clarity as to where to find the clusterid where to use it and also adds it into a couple of document pages where the information was missing.
Why this way
The hope is to provide clear concise documentation that will help users quickly integrate klaw with their organisation.
Signed-off-by: Aindriu Lavelle <aindriu.lavelle@aiven.io>
> Promotion of Topics and Schemas

- docs/docs/howto/authentication/third-party-account.rst
Signed-off-by: Aindriu Lavelle <aindriu.lavelle@aiven.io>
About this change:
This change adds a small piece of information for users to be able to configure their third party providers.
Why This way
This way simplifies and minimises the amount of additional work a user needs to do.
> Documentation for third party authentication providers

- docs/conf.py
Fixes #46 
I could not reproduce the bug locally, since the markup was not correctly rendered for unknown reasons (see screenshot, left locally, right prod).
But the style in question is based on `[role="main"] . highlighted` so I just faked that locally to check if the variable update works. 
Screenshot local
> fix: Add variable for highlighted text to fix appearance in dark mode.

- docs/docs/concepts/workflows.rst
Allow Users to see who is required to approve the different types of requests in Klaw.
> Update Workflows to include an approval table

- docs/docs/howto/installation/run-source.rst
- docs/releases/release240.rst
Since release 2.4.0 the coral preview is enabled by default. This PR updates:
- the docs how to setup Klaw from source -> informs user that React UI is enabled by default and how to disabled it if they want to
- the release notes for 2.4.0 -> same as above it informs user how to disable the preview if they want to
> Update docs regarding coral enabled default

- src/css/custom.css
This PR fixes #89 
- Remove font-setting via custom css for headlines and paragraphs  and set correct values for existing global variables. 
- Remove custom a style and style links by setting correct values for existing global variables. 
- Remove `.muted-link` class as it's never used and does not relate to a Infima class
- Remove `.custom-note` class as it's never used and does not relate to a Infima class
> (fix): Update custom css

- CONTRIBUTING.md
- STYLEGUIDE.md
This PR adds a `STYLEGUIDE.md` to our tech-docs to describe our Klaw styles and tone more in depth. The styleguide will grow over time :)  and help people contributing to the docs to be consistent in their writing. 
For now, it's mostly information about capitalisation of words and is based on the great explanation from the awesome @harshini-rangaswamy (Credit where credit's due!)
> Add first entries to style guide

- .github/vale/styles/Klaw/branding-warning-temp.yml
- .github/vale/styles/Klaw/branding.yml
- docs/HowTo/clusterconnectivity/aiven-kafka-cluster-sasl-ssl-protocol.md
This PR will fixes #104 which is Update docs to use the term "Klaw" correctly.
Fixes #104 
After updating code and run ```npm run spell:error``` Here is the result:)
This will fallow code of conduct as of my knowledge.
For further queries feel free to connect.
Hope this will merge as soon as possible.
Happy coding🤝.
> fixes: Update doc term klaw correctly

- .github/vale/styles/Klaw/branding-warning-temp.yml
- .github/vale/styles/Klaw/branding.yml
- .github/workflows/vale.yaml
- STYLEGUIDE.md
- package.json
I noticed that our vale action is not running as expected. 
It does not raise errors even so it logs them. 
This seems to be related to reviewdog, which is used by the vale action. While I got it to work fine (I think, based on my testing) with checking the files that are in the diff, I didn't get it to fail on errors in other files, even so the errors are clearly there and even logged. 
After a bit of research I found this issue: https://github.com/reviewdog/reviewdog/issues/1408 
and based my fix on that. I've confirmed that this works as expected, at least on this PR for now. 
- changes the vale workflow to cover all markdown files correctly
- fixes a spelling issue that did went under the radar of the action before
- removes a branding rule for "Klaw" as error and adds it in the temp …
> (ci) Update vale workflow reporter

- .github/vale/styles/Klaw/branding-warning-temp.yml
- .github/vale/styles/Klaw/branding.yml
- docs/HowTo/clusterconnectivity/confluent-cloud-kafka-cluster-ssl-protocol.md
Description
I have made the changes in branding.yml and branding-warning-temp.yml files to help docs use the term "Confluent Cloud" correctly.
Notes for Reviewers
Test:   npm run spell: error was green, no spelling errors found.
npm run spell:error                             
> klaw-docs@1.0.0 spell:error
> vale --glob='!.github/vale/styles/*' . --minAlertLevel=error
✔ 0 errors, 0 warnings and 0 suggestions in 0 files.
Please check the above changes if I did anything wrong please let me know.
This PR fixes #100
> Updated branding.yml and respective files to help docs to use the term "Confluent Cloud" correctly.

- docs/Concepts/high-availability.md
There were some new configuration properties added into the application.properties that are required to be added to the documentation for HIgh Availability.
> Add new configuration to enabling HA in Klaw

- .github/vale/styles/Klaw/first-postgresql-registered.yml
- blog/2023/07/high-availability-for-klaw.md
- docs/HowTo/clusterconnectivity/klaw-db-connection.md
- Fixes the usage of trademark in PostgreSQL.
`npm run spell:error` was green, no spelling errors found.
- fixes  #109 
Author: Rajat Gupta <@morgoth9808>
> (fix) Update correct usage of copyright for PostgreSQL#109

- .github/vale/styles/Klaw/branding-warning-temp.yml
- .github/vale/styles/Klaw/branding.yml
- docs/HowTo/clusterconnectivity/aiven-kafka-cluster-ssl-protocol.md
- docs/HowTo/clusterconnectivity/aiven-kafka-connect-cluster-ssl-protocol.md
- docs/HowTo/clusterconnectivity/aiven-karapace-cluster-ssl-protocol.md
- docs/HowTo/clusterconnectivity/confluent-cloud-kafka-cluster-ssl-protocol.md
- docs/HowTo/clusterconnectivity/kafka-cluster-sasl-ssl-protocol.md
- docs/HowTo/clusterconnectivity/kafka-cluster-ssl-protocol.md
- docs/HowTo/clusterconnectivity/klaw-core-with-clusterapi.md
- docs/HowTo/clusterconnectivity/sr-cluster-ssl-protocol.md
- docs/HowTo/installation/run-source.md
- docs/Releases/release110.md
- docs/Releases/release240.md
- docs/Releases/release250.md
- docs/Releases/release251.md
Cut and past the line related to API ("(?i)api") from branding-warning-temp.yml and add it to branding.yaml
Run npm run spell:error and revise all the wrong uses according to the result.
After revising, no errors:
Closes #101
> use term "API" correctly

- docs/quickstart.md
- src/components/QuickStartRow/index.jsx
Change the Quickstart to use the nightly which has an update allowing it to be switched to using a SSL security protocol and also added a piece of configuration which prevents an erroneous error from occuring.
> Resolve a configuration error and also switch to using the nightly build to use a new Quickstart feature

- docs/HowTo/installation/run-docker.md
There is a default https setting introduced in 2.6.0 and this minor addition overrides that default setting to make it easier to get up and running in a http environment to try Klaw out.
> Update docker yaml to override https default setting

- docusaurus.config.js
- snowplow.js
- src/components/HomepageFeatures/index.js
While Docusarus generates static HTML files, it uses client-site routing for a smoother experience. That's why we have to call the page view tracking on every route change. 
see:
- https://github.com/facebook/docusaurus/issues/3399
- https://github.com/snowplow/documentation/blob/main/snowplow.js
Note
- this PR also fixes a prop-type
> Update snowplow config

- .github/vale/styles/Klaw/branding-warning-temp.yml
- .github/vale/styles/Klaw/branding.yml
- blog/2023/07/high-availability-for-klaw.md
- docs/Concepts/high-availability.md
- docs/HowTo/authentication/azure-ad.md
- docs/HowTo/authentication/google-account.md
- docs/HowTo/authentication/third-party-account.md
- docs/HowTo/authentication/windows-ad.md
- docs/HowTo/clusterconnectivity/aiven-kafka-cluster-sasl-ssl-protocol.md
- docs/HowTo/clusterconnectivity/aiven-kafka-cluster-ssl-protocol.md
- docs/HowTo/clusterconnectivity/aiven-kafka-connect-cluster-ssl-protocol.md
- docs/HowTo/clusterconnectivity/aiven-karapace-cluster-ssl-protocol.md
- docs/HowTo/clusterconnectivity/confluent-cloud-kafka-cluster-ssl-protocol.md
- docs/HowTo/clusterconnectivity/kafka-cluster-sasl-ssl-protocol.md
- docs/HowTo/clusterconnectivity/kafka-cluster-ssl-protocol.md
- docs/HowTo/clusterconnectivity/klaw-core-with-clusterapi.md
- docs/HowTo/clusterconnectivity/klaw-db-connection.md
- docs/HowTo/clusterconnectivity/sr-cluster-ssl-protocol.md
- docs/HowTo/installation/run-docker.md
- docs/HowTo/installation/run-source.md
- docs/HowTo/notifications/email-notification.md
- docs/HowTo/settings.md
- docs/Releases/release200.md
- docs/Releases/release250.md
- docs/Releases/release251.md
- docs/Releases/release260.md
- docs/index.md
This PR:
- adds the rule for correct usage of "Klaw Core" as error
- extends existing rule for "Klaw Cluster API"
- updates usage of wrong spelling in markdown
Resolves #103
> Update usage of "Klaw Core"

- README.md
- docs/HowTo/clusterconnectivity/confluent-cloud-kafka-cluster-ssl-protocol.md
- docs/HowTo/deployklaw.md
- docs/HowTo/installation/run-docker.md
- docs/HowTo/settings.md
- docs/HowTo/zothers.md
- docs/Releases/release100.md
- docs/Releases/release110.md
- docs/Releases/release120.md
- docs/Releases/release200.md
- docs/Releases/release210.md
- docs/Releases/release220.md
- docs/Releases/release230.md
- docs/Releases/release240.md
- docs/Releases/release250.md
- docs/Releases/release251.md
- docs/Releases/release252.md
- docs/Releases/release260.md
- docs/Releases/release261.md
- docs/getstarted.md
- docs/index.md
- docusaurus.config.js
- package-lock.json
- package.json
This PR:
- fixed md(x) formatting to prepare for updating mdx version
- updates dependencies to use docusaurus v3
~~This PR will stay in draft until [git push --set-upstream origin [chore(debug-plugin): migrate to a new maintained JSON Viewer](https://github.com/facebook/docusaurus/pull/9566) is released to avoid dependency conflicts that is caused by `@docusaurus/plugin-debug` deps.~~
Just a few hours later, released 🎉  https://github.com/facebook/docusaurus/releases
> chore: Update docusaurus to v3

- docs/releases/release280.md
- docs/releases/release281.md
Quick release notes for a patch release of Klaw 2.8.1 to fix a small bug introduced in 2.8.0 which removed the ability to user email ids as usernames for new users.
> Add release notes for release 2.8.1

- .github/vale/styles/Klaw/spelling-klaw-vocabulary.txt
- docs/releases/release280.md
- docs/releases/release290.md
- docs/workflows/subscription/claim-subscription.md
- sidebars.js
Adding Release 2.9.0 release notes.
Also adding some information and caveats around BETA feature claim subscriptions
> Release290

- blog/2023/05/effortless-kafka-governance-making-life-easier-for-developers.md
- blog/2023/07/high-availability-for-klaw.md
- blog/2023/09/schema-management-disaster-recovery-in-klaw.md
- blog/2023/11/important-community-update-klaws-latest-actions-to-enhance-transparency.md
- docusaurus.config.js
- package.json
- pnpm-lock.yaml
Resolves  issue #250 
This PR
- update Docusaurus and related packages to version `3.5`
- adds name to custom plugin (is now required)
**Additionally:**
Adds truncate marks to blogs, this is now recommended and shows a warning otherwise. This means that in our blog overview page, we will not see all blog posts in full length, but only see content until the truncate mark and then a read more button.
**Screenshot**
> deps: Update docusaurus

- .github/vale/styles/Klaw/branding.yml
- .github/vale/styles/Klaw/spelling-klaw-vocabulary.txt
- README.md
- docs/authentication-authorization/authentication/userpwd-db.md
- docs/releases/release2100.md
- adds release notes for v2.10.0
- corrects script description for Vale script in README
- adds word `Keycloak` to our Vale rules
> Release notes Klaw v2.10.0
