Aiven-Open/klaw-docs

- docs/docs/config.rst
About this change - What it does
Documentation to Configure Klaw to handle multiple clusters with different SSL configurations
> Multiple ssl config to connect to multiple clusters with ssl protocol

- docs/docs/clusters-environments.rst
Adding Kafka supported protocols
> Adding supported protocols

- docs/_templates/header.html
- docs/contents.rst
- docs/releases.rst
- docs/releases/release100.rst
- docs/releases/release110.rst
Adding Releases section with a brief description of each release and link to git tag.
> Adding releases section

- docs/releases/release120.rst
> fixed a typo

- docs/_static/js/snowplow.js
This is the new version that we are running on the collector side.
> Update snowplow postPath parameter to new value

- docs/docs/howto.rst
- docs/docs/howto/authorization.rst
- docs/docs/howto/clusterconnectivity/aiven-kafka-cluster-ssl-protocol.rst
- docs/docs/howto/clusterconnectivity/aiven-kafka-connect-cluster-ssl-protocol.rst
- docs/docs/howto/clusterconnectivity/aiven-karapace-cluster-ssl-protocol.rst
- docs/docs/howto/clusterconnectivity/kafka-cluster-ssl-protocol.rst
- Add authorization section
- Fix some content in connectivity
> Add Authorization section

- docs/docs/howto.rst
- docs/docs/howto/exportdata.rst
> Docs for export data feature

- docs/docs/howto/installation/run-docker.rst
Add additional documentation on how to enable https on docker deployed Klaw
> Enhanced docker documentation for installation

- docs/_static/css/klaw.css
- docs/conf.py
- docs/docs/howto.rst
- docs/docs/howto/kafka-cluster-migration.rst
- docs/docs/howto/notifications.rst
- docs/docs/howto/notifications/email-notification.rst
- docs/releases.rst
Additional information on emails that are sent out on which actions and where they can be edited
> Initial commit on the table of notifications for emails

- docs/releases.rst
- docs/releases/release240.rst
> Adding rel 240

- docs/docs/howto/installation/run-docker.rst
- docs/docs/howto/installation/run-source.rst
This adds a prereq part to the docker install. 
It also fixes an indent issue with the docker-compose.yaml
> Improved Docker installation instructions.

- docs/docs/Releases/release240.md
Add download links to 2.4.0 release
> Add download links

- docs/docusaurus.config.js
- docs/package.json
Search pages with Algolia (Docusaurus support)
> Adding search bar

- docs/docs/Concepts/users-teams.md
- docs/docs/quickstart.md
- docs/src/components/HomepageFeatures/index.js
- docs/src/components/HomepageFeatures/styles.module.css
- docs/src/components/QuickStartRow/index.jsx
This PR adds very rudimentary accessibility improvements. It's mostly semantics. 
This does **not** cover 
- colours / font
- keyboard support
- screenreader support
> Rudimentary accessibility improvements

- docs/src/components/HomepageFeatures/index.js
- docs/src/components/QuickStartRow/index.jsx
Anchor links for quickstart and keyfeatures
> Adding anchor links

- docs/docs/Releases/release251.md
Adds the release page for 2.5.1
> Add the release page for 2.5.1

- .githooks/pre-commit
- .github/vale/dicts/klaw.dic
- .vale.ini
- CONTRIBUTING.md
- README.md
- package.json
This PR:
- adds CONTRIBUTING.md file
- updates README minimal
> Add tech docs for contributing

- .github/vale/styles/Klaw/first-postgresql-registered.yml
- .github/vale/styles/Klaw/language-condescending.yml
- .github/vale/styles/Klaw/language-race.yml
- docs/Releases/release100.md
- add rule for correct registering of "PostgreSQL" (follow up issue for hacktoberfest will follow)
- add rule for race related words and fix one isse 
- add rule to warn about potential condescending language   (follow up issue for hacktoberfest will follow)
> Add additional rules

- .github/vale/styles/Klaw/branding-warning-temp.yml
- .github/vale/styles/Klaw/branding.yml
- docs/Releases/release110.md
This PR fixes issue #105 
Plz check and let me know if more changes are required in this issue.
> Update docs to use SSL correctly

- .github/vale/styles/Klaw/spelling-klaw-vocabulary.txt
- docs/HowTo/clusterconnectivity/aiven-kafka-connect-cluster-ssl-protocol.md
- docs/HowTo/clusterconnectivity/aiven-karapace-cluster-ssl-protocol.md
- docs/HowTo/installation/run-docker.md
- docs/HowTo/installation/run-source.md
- Update superadmin password
- run script option is added
> Update pwd, run script

- docs/quickstart.md
- src/components/QuickStartRow/index.jsx
so that the newest features can be quickly tested.
> Update Quickstart to use the latest release of Klaw 

- docusaurus.config.js
- package-lock.json
- package.json
Our current usage is not GDPR conform, we will remove it until we've done that.
> Remove search plugin temporary

- README.md
- docs/Releases/release260.md
This PR:
- updates a few broken links
> Update broken links

- .github/vale/styles/Klaw/branding-warning-temp.yml
- .github/vale/styles/Klaw/branding.yml
- README.md
- docs/HowTo/authentication/google-account.md
- docs/HowTo/authentication/userpwd-db.md
- docs/HowTo/clusterconnectivity/klaw-core-with-clusterapi.md
- docs/HowTo/installation/configure-klaw-wizard.md
- docs/HowTo/installation/run-source.md
- docs/HowTo/kafka-cluster-migration/sync-connectors-from-cluster.md
- docs/Releases/release100.md
- docs/Releases/release110.md
- docs/Releases/release240.md
- docs/Releases/release250.md
- docs/Releases/release251.md
- docs/Releases/release260.md
This PR:
- moves rule for "Klaw" into branding (errors) 
- updates wrong usage of Klaw 
Resolves #133
> Update "Klaw" usage

- docs/Concepts/promotion.md
- docs/HowTo/schemas/Promote-a-schema.md
- docs/HowTo/topics/Promote-a-topic.md
> refactor: split content for promotion

- .github/vale/styles/Klaw/extraneous-apostrophes.yml
- .github/vale/styles/Klaw/spelling-klaw-vocabulary.txt
- blog/2023/11/important-community-update-klaws-latest-actions-to-enhance-transparency.md
- blog/authors.yml
- docs/HowTo/installation/run-docker.md
- docs/Releases/release252.md
- docs/Releases/release261.md
Update Release documentation for 252 and 261 and add explanatory blog post
> Update Release documentation for 252 and 261 and add explanatory blog post

- docs/Concepts/high-availability.md
> fix: Fix code block formatting in High Availability page

- .github/dependabot.yml
This PR adds dependabot to handle dependency updates.
> ci: Add dependabot to handle dependency updates

- package.json
- pnpm-lock.yaml
The package is not used in our code or any other package, so it can be removed.
> dep: Remove unused package react-player

- package.json
- pnpm-lock.yaml
Those updated need to go in together
> deps: Update docusaurus core and preset package
